// Autogenerated with StateSmith 0.22.2+0c32be37bf4d4fee5499780a5ef37a7996c192f9.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

/*
 * Generated from v_model/05_mbd_state_machine/statesmith_model/FailoverSupervisor.plantuml.
 * Do not edit generated files manually. Update the model and regenerate.
 */

#include "FailoverSupervisor.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
#include "SupervisorMbd_Port.h"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(FailoverSupervisor* sm, FailoverSupervisor_StateId desired_state);

static void ROOT_enter(FailoverSupervisor* sm);

static void DEGRADED_enter(FailoverSupervisor* sm);

static void DEGRADED_exit(FailoverSupervisor* sm);

static void DEGRADED_ev_critical_fault(FailoverSupervisor* sm);

static void DEGRADED_ev_primary_recovery_detected(FailoverSupervisor* sm);

static void FAILOVER_IN_PROGRESS_enter(FailoverSupervisor* sm);

static void FAILOVER_IN_PROGRESS_exit(FailoverSupervisor* sm);

static void FAILOVER_IN_PROGRESS_ev_backup_activation_timeout(FailoverSupervisor* sm);

static void FAILOVER_IN_PROGRESS_ev_backup_active_ack(FailoverSupervisor* sm);

static void INIT_enter(FailoverSupervisor* sm);

static void INIT_exit(FailoverSupervisor* sm);

static void INIT_ev_init_done(FailoverSupervisor* sm);

static void NORMAL_enter(FailoverSupervisor* sm);

static void NORMAL_exit(FailoverSupervisor* sm);

static void NORMAL_ev_critical_fault(FailoverSupervisor* sm);

static void NORMAL_ev_primary_heartbeat_ok(FailoverSupervisor* sm);

static void NORMAL_ev_primary_heartbeat_timeout(FailoverSupervisor* sm);

static void PRIMARY_FAULT_CANDIDATE_enter(FailoverSupervisor* sm);

static void PRIMARY_FAULT_CANDIDATE_exit(FailoverSupervisor* sm);

static void PRIMARY_FAULT_CANDIDATE_ev_fault_confirmation_reached(FailoverSupervisor* sm);

static void PRIMARY_FAULT_CANDIDATE_ev_primary_heartbeat_ok(FailoverSupervisor* sm);

static void RECOVERY_DETECTED_enter(FailoverSupervisor* sm);

static void RECOVERY_DETECTED_exit(FailoverSupervisor* sm);

static void RECOVERY_DETECTED_ev_critical_fault(FailoverSupervisor* sm);

static void RECOVERY_DETECTED_ev_manual_failback_approved(FailoverSupervisor* sm);

static void RECOVERY_DETECTED_ev_primary_heartbeat_ok(FailoverSupervisor* sm);

static void SAFE_enter(FailoverSupervisor* sm);

static void SAFE_exit(FailoverSupervisor* sm);

static void SAFE_ev_primary_heartbeat_ok(FailoverSupervisor* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void FailoverSupervisor_ctor(FailoverSupervisor* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void FailoverSupervisor_start(FailoverSupervisor* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(INIT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `INIT`.
            INIT_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void FailoverSupervisor_dispatch_event(FailoverSupervisor* sm, FailoverSupervisor_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: FailoverSupervisor
        case FailoverSupervisor_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: DEGRADED
        case FailoverSupervisor_StateId_DEGRADED:
            switch (event_id)
            {
                case FailoverSupervisor_EventId_EV_PRIMARY_RECOVERY_DETECTED: DEGRADED_ev_primary_recovery_detected(sm); break;
                case FailoverSupervisor_EventId_EV_CRITICAL_FAULT: DEGRADED_ev_critical_fault(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: FAILOVER_IN_PROGRESS
        case FailoverSupervisor_StateId_FAILOVER_IN_PROGRESS:
            switch (event_id)
            {
                case FailoverSupervisor_EventId_EV_BACKUP_ACTIVE_ACK: FAILOVER_IN_PROGRESS_ev_backup_active_ack(sm); break;
                case FailoverSupervisor_EventId_EV_BACKUP_ACTIVATION_TIMEOUT: FAILOVER_IN_PROGRESS_ev_backup_activation_timeout(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: INIT
        case FailoverSupervisor_StateId_INIT:
            switch (event_id)
            {
                case FailoverSupervisor_EventId_EV_INIT_DONE: INIT_ev_init_done(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: NORMAL
        case FailoverSupervisor_StateId_NORMAL:
            switch (event_id)
            {
                case FailoverSupervisor_EventId_EV_PRIMARY_HEARTBEAT_OK: NORMAL_ev_primary_heartbeat_ok(sm); break;
                case FailoverSupervisor_EventId_EV_PRIMARY_HEARTBEAT_TIMEOUT: NORMAL_ev_primary_heartbeat_timeout(sm); break;
                case FailoverSupervisor_EventId_EV_CRITICAL_FAULT: NORMAL_ev_critical_fault(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: PRIMARY_FAULT_CANDIDATE
        case FailoverSupervisor_StateId_PRIMARY_FAULT_CANDIDATE:
            switch (event_id)
            {
                case FailoverSupervisor_EventId_EV_PRIMARY_HEARTBEAT_OK: PRIMARY_FAULT_CANDIDATE_ev_primary_heartbeat_ok(sm); break;
                case FailoverSupervisor_EventId_EV_FAULT_CONFIRMATION_REACHED: PRIMARY_FAULT_CANDIDATE_ev_fault_confirmation_reached(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: RECOVERY_DETECTED
        case FailoverSupervisor_StateId_RECOVERY_DETECTED:
            switch (event_id)
            {
                case FailoverSupervisor_EventId_EV_PRIMARY_HEARTBEAT_OK: RECOVERY_DETECTED_ev_primary_heartbeat_ok(sm); break;
                case FailoverSupervisor_EventId_EV_MANUAL_FAILBACK_APPROVED: RECOVERY_DETECTED_ev_manual_failback_approved(sm); break;
                case FailoverSupervisor_EventId_EV_CRITICAL_FAULT: RECOVERY_DETECTED_ev_critical_fault(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: SAFE
        case FailoverSupervisor_StateId_SAFE:
            switch (event_id)
            {
                case FailoverSupervisor_EventId_EV_PRIMARY_HEARTBEAT_OK: SAFE_ev_primary_heartbeat_ok(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(FailoverSupervisor* sm, FailoverSupervisor_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case FailoverSupervisor_StateId_DEGRADED: DEGRADED_exit(sm); break;
            
            case FailoverSupervisor_StateId_FAILOVER_IN_PROGRESS: FAILOVER_IN_PROGRESS_exit(sm); break;
            
            case FailoverSupervisor_StateId_INIT: INIT_exit(sm); break;
            
            case FailoverSupervisor_StateId_NORMAL: NORMAL_exit(sm); break;
            
            case FailoverSupervisor_StateId_PRIMARY_FAULT_CANDIDATE: PRIMARY_FAULT_CANDIDATE_exit(sm); break;
            
            case FailoverSupervisor_StateId_RECOVERY_DETECTED: RECOVERY_DETECTED_exit(sm); break;
            
            case FailoverSupervisor_StateId_SAFE: SAFE_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state DEGRADED
////////////////////////////////////////////////////////////////////////////////

static void DEGRADED_enter(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_DEGRADED;
    
    // DEGRADED behavior
    // uml: enter / { SupervisorMbd_logStateEntry("DEGRADED"); }
    {
        // Step 1: execute action `SupervisorMbd_logStateEntry("DEGRADED");`
        SupervisorMbd_logStateEntry("DEGRADED");
    } // end of behavior for DEGRADED
}

static void DEGRADED_exit(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_ROOT;
}

static void DEGRADED_ev_critical_fault(FailoverSupervisor* sm)
{
    // DEGRADED behavior
    // uml: EV_CRITICAL_FAULT / { SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("DEGRADED", "SAFE"); } TransitionTo(SAFE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        DEGRADED_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("DEGRADED", "SAFE");`.
        SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("DEGRADED", "SAFE");
        
        // Step 3: Enter/move towards transition target `SAFE`.
        SAFE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for DEGRADED
    
    // No ancestor handles this event.
}

static void DEGRADED_ev_primary_recovery_detected(FailoverSupervisor* sm)
{
    // DEGRADED behavior
    // uml: EV_PRIMARY_RECOVERY_DETECTED / { SupervisorMbd_logEvent("PRIMARY_RECOVERY_DETECTED"); } TransitionTo(RECOVERY_DETECTED)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        DEGRADED_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_logEvent("PRIMARY_RECOVERY_DETECTED");`.
        SupervisorMbd_logEvent("PRIMARY_RECOVERY_DETECTED");
        
        // Step 3: Enter/move towards transition target `RECOVERY_DETECTED`.
        RECOVERY_DETECTED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for DEGRADED
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FAILOVER_IN_PROGRESS
////////////////////////////////////////////////////////////////////////////////

static void FAILOVER_IN_PROGRESS_enter(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_FAILOVER_IN_PROGRESS;
    
    // FAILOVER_IN_PROGRESS behavior
    // uml: enter / { SupervisorMbd_logStateEntry("FAILOVER_IN_PROGRESS"); }
    {
        // Step 1: execute action `SupervisorMbd_logStateEntry("FAILOVER_IN_PROGRESS");`
        SupervisorMbd_logStateEntry("FAILOVER_IN_PROGRESS");
    } // end of behavior for FAILOVER_IN_PROGRESS
}

static void FAILOVER_IN_PROGRESS_exit(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_ROOT;
}

static void FAILOVER_IN_PROGRESS_ev_backup_activation_timeout(FailoverSupervisor* sm)
{
    // FAILOVER_IN_PROGRESS behavior
    // uml: EV_BACKUP_ACTIVATION_TIMEOUT / { SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("FAILOVER_IN_PROGRESS", "SAFE"); } TransitionTo(SAFE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        FAILOVER_IN_PROGRESS_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("FAILOVER_IN_PROGRESS", "SAFE");`.
        SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("FAILOVER_IN_PROGRESS", "SAFE");
        
        // Step 3: Enter/move towards transition target `SAFE`.
        SAFE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FAILOVER_IN_PROGRESS
    
    // No ancestor handles this event.
}

static void FAILOVER_IN_PROGRESS_ev_backup_active_ack(FailoverSupervisor* sm)
{
    // FAILOVER_IN_PROGRESS behavior
    // uml: EV_BACKUP_ACTIVE_ACK / { SupervisorMbd_stopBackupActivationTimer(); SupervisorMbd_setActiveOwnerBackup(); SupervisorMbd_logTransition("FAILOVER_IN_PROGRESS", "DEGRADED"); } TransitionTo(DEGRADED)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        FAILOVER_IN_PROGRESS_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_stopBackupActivationTimer(); SupervisorMbd_setActiveOwnerBackup(); SupervisorMbd_logTransition("FAILOVER_IN_PROGRESS", "DEGRADED");`.
        SupervisorMbd_stopBackupActivationTimer(); SupervisorMbd_setActiveOwnerBackup(); SupervisorMbd_logTransition("FAILOVER_IN_PROGRESS", "DEGRADED");
        
        // Step 3: Enter/move towards transition target `DEGRADED`.
        DEGRADED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FAILOVER_IN_PROGRESS
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state INIT
////////////////////////////////////////////////////////////////////////////////

static void INIT_enter(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_INIT;
    
    // INIT behavior
    // uml: enter / { SupervisorMbd_logStateEntry("INIT"); }
    {
        // Step 1: execute action `SupervisorMbd_logStateEntry("INIT");`
        SupervisorMbd_logStateEntry("INIT");
    } // end of behavior for INIT
}

static void INIT_exit(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_ROOT;
}

static void INIT_ev_init_done(FailoverSupervisor* sm)
{
    // INIT behavior
    // uml: EV_INIT_DONE / { SupervisorMbd_setActiveOwnerPrimary(); SupervisorMbd_logTransition("INIT", "NORMAL"); } TransitionTo(NORMAL)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        INIT_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_setActiveOwnerPrimary(); SupervisorMbd_logTransition("INIT", "NORMAL");`.
        SupervisorMbd_setActiveOwnerPrimary(); SupervisorMbd_logTransition("INIT", "NORMAL");
        
        // Step 3: Enter/move towards transition target `NORMAL`.
        NORMAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for INIT
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state NORMAL
////////////////////////////////////////////////////////////////////////////////

static void NORMAL_enter(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_NORMAL;
    
    // NORMAL behavior
    // uml: enter / { SupervisorMbd_logStateEntry("NORMAL"); }
    {
        // Step 1: execute action `SupervisorMbd_logStateEntry("NORMAL");`
        SupervisorMbd_logStateEntry("NORMAL");
    } // end of behavior for NORMAL
}

static void NORMAL_exit(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_ROOT;
}

static void NORMAL_ev_critical_fault(FailoverSupervisor* sm)
{
    // NORMAL behavior
    // uml: EV_CRITICAL_FAULT / { SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("NORMAL", "SAFE"); } TransitionTo(SAFE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NORMAL_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("NORMAL", "SAFE");`.
        SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("NORMAL", "SAFE");
        
        // Step 3: Enter/move towards transition target `SAFE`.
        SAFE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for NORMAL
    
    // No ancestor handles this event.
}

static void NORMAL_ev_primary_heartbeat_ok(FailoverSupervisor* sm)
{
    // NORMAL behavior
    // uml: EV_PRIMARY_HEARTBEAT_OK / { SupervisorMbd_resetPrimaryFaultCounter(); }
    {
        // Step 1: execute action `SupervisorMbd_resetPrimaryFaultCounter();`
        SupervisorMbd_resetPrimaryFaultCounter();
    } // end of behavior for NORMAL
    
    // No ancestor handles this event.
}

static void NORMAL_ev_primary_heartbeat_timeout(FailoverSupervisor* sm)
{
    // NORMAL behavior
    // uml: EV_PRIMARY_HEARTBEAT_TIMEOUT / { SupervisorMbd_incrementPrimaryFaultCounter(); SupervisorMbd_logEvent("PRIMARY_HEARTBEAT_TIMEOUT"); } TransitionTo(PRIMARY_FAULT_CANDIDATE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        NORMAL_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_incrementPrimaryFaultCounter(); SupervisorMbd_logEvent("PRIMARY_HEARTBEAT_TIMEOUT");`.
        SupervisorMbd_incrementPrimaryFaultCounter(); SupervisorMbd_logEvent("PRIMARY_HEARTBEAT_TIMEOUT");
        
        // Step 3: Enter/move towards transition target `PRIMARY_FAULT_CANDIDATE`.
        PRIMARY_FAULT_CANDIDATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for NORMAL
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state PRIMARY_FAULT_CANDIDATE
////////////////////////////////////////////////////////////////////////////////

static void PRIMARY_FAULT_CANDIDATE_enter(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_PRIMARY_FAULT_CANDIDATE;
    
    // PRIMARY_FAULT_CANDIDATE behavior
    // uml: enter / { SupervisorMbd_logStateEntry("PRIMARY_FAULT_CANDIDATE"); }
    {
        // Step 1: execute action `SupervisorMbd_logStateEntry("PRIMARY_FAULT_CANDIDATE");`
        SupervisorMbd_logStateEntry("PRIMARY_FAULT_CANDIDATE");
    } // end of behavior for PRIMARY_FAULT_CANDIDATE
}

static void PRIMARY_FAULT_CANDIDATE_exit(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_ROOT;
}

static void PRIMARY_FAULT_CANDIDATE_ev_fault_confirmation_reached(FailoverSupervisor* sm)
{
    // PRIMARY_FAULT_CANDIDATE behavior
    // uml: EV_FAULT_CONFIRMATION_REACHED / { SupervisorMbd_declarePrimaryFault(); SupervisorMbd_isolatePrimary(); SupervisorMbd_requestBackupActivation(); SupervisorMbd_startBackupActivationTimer(); SupervisorMbd_logTransition("PRIMARY_FAULT_CANDIDATE", "FAILOVER_IN_PROGRESS"); } TransitionTo(FAILOVER_IN_PROGRESS)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        PRIMARY_FAULT_CANDIDATE_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_declarePrimaryFault(); SupervisorMbd_isolatePrimary(); SupervisorMbd_requestBackupActivation(); SupervisorMbd_startBackupActivationTimer(); SupervisorMbd_logTransition("PRIMARY_FAULT_CANDIDATE", "FAILOVER_IN_PROGRESS");`.
        SupervisorMbd_declarePrimaryFault(); SupervisorMbd_isolatePrimary(); SupervisorMbd_requestBackupActivation(); SupervisorMbd_startBackupActivationTimer(); SupervisorMbd_logTransition("PRIMARY_FAULT_CANDIDATE", "FAILOVER_IN_PROGRESS");
        
        // Step 3: Enter/move towards transition target `FAILOVER_IN_PROGRESS`.
        FAILOVER_IN_PROGRESS_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PRIMARY_FAULT_CANDIDATE
    
    // No ancestor handles this event.
}

static void PRIMARY_FAULT_CANDIDATE_ev_primary_heartbeat_ok(FailoverSupervisor* sm)
{
    // PRIMARY_FAULT_CANDIDATE behavior
    // uml: EV_PRIMARY_HEARTBEAT_OK / { SupervisorMbd_resetPrimaryFaultCounter(); SupervisorMbd_logTransition("PRIMARY_FAULT_CANDIDATE", "NORMAL"); } TransitionTo(NORMAL)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        PRIMARY_FAULT_CANDIDATE_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_resetPrimaryFaultCounter(); SupervisorMbd_logTransition("PRIMARY_FAULT_CANDIDATE", "NORMAL");`.
        SupervisorMbd_resetPrimaryFaultCounter(); SupervisorMbd_logTransition("PRIMARY_FAULT_CANDIDATE", "NORMAL");
        
        // Step 3: Enter/move towards transition target `NORMAL`.
        NORMAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PRIMARY_FAULT_CANDIDATE
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state RECOVERY_DETECTED
////////////////////////////////////////////////////////////////////////////////

static void RECOVERY_DETECTED_enter(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_RECOVERY_DETECTED;
    
    // RECOVERY_DETECTED behavior
    // uml: enter / { SupervisorMbd_logStateEntry("RECOVERY_DETECTED"); }
    {
        // Step 1: execute action `SupervisorMbd_logStateEntry("RECOVERY_DETECTED");`
        SupervisorMbd_logStateEntry("RECOVERY_DETECTED");
    } // end of behavior for RECOVERY_DETECTED
}

static void RECOVERY_DETECTED_exit(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_ROOT;
}

static void RECOVERY_DETECTED_ev_critical_fault(FailoverSupervisor* sm)
{
    // RECOVERY_DETECTED behavior
    // uml: EV_CRITICAL_FAULT / { SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("RECOVERY_DETECTED", "SAFE"); } TransitionTo(SAFE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        RECOVERY_DETECTED_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("RECOVERY_DETECTED", "SAFE");`.
        SupervisorMbd_enterSafeState(); SupervisorMbd_logTransition("RECOVERY_DETECTED", "SAFE");
        
        // Step 3: Enter/move towards transition target `SAFE`.
        SAFE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for RECOVERY_DETECTED
    
    // No ancestor handles this event.
}

static void RECOVERY_DETECTED_ev_manual_failback_approved(FailoverSupervisor* sm)
{
    // RECOVERY_DETECTED behavior
    // uml: EV_MANUAL_FAILBACK_APPROVED / { SupervisorMbd_requestBackupStandby(); SupervisorMbd_setActiveOwnerPrimary(); SupervisorMbd_resetPrimaryFaultCounter(); SupervisorMbd_logTransition("RECOVERY_DETECTED", "NORMAL"); } TransitionTo(NORMAL)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        RECOVERY_DETECTED_exit(sm);
        
        // Step 2: Transition action: `SupervisorMbd_requestBackupStandby(); SupervisorMbd_setActiveOwnerPrimary(); SupervisorMbd_resetPrimaryFaultCounter(); SupervisorMbd_logTransition("RECOVERY_DETECTED", "NORMAL");`.
        SupervisorMbd_requestBackupStandby(); SupervisorMbd_setActiveOwnerPrimary(); SupervisorMbd_resetPrimaryFaultCounter(); SupervisorMbd_logTransition("RECOVERY_DETECTED", "NORMAL");
        
        // Step 3: Enter/move towards transition target `NORMAL`.
        NORMAL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for RECOVERY_DETECTED
    
    // No ancestor handles this event.
}

static void RECOVERY_DETECTED_ev_primary_heartbeat_ok(FailoverSupervisor* sm)
{
    // RECOVERY_DETECTED behavior
    // uml: EV_PRIMARY_HEARTBEAT_OK / { SupervisorMbd_logEvent("PRIMARY_STILL_RECOVERED"); }
    {
        // Step 1: execute action `SupervisorMbd_logEvent("PRIMARY_STILL_RECOVERED");`
        SupervisorMbd_logEvent("PRIMARY_STILL_RECOVERED");
    } // end of behavior for RECOVERY_DETECTED
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SAFE
////////////////////////////////////////////////////////////////////////////////

static void SAFE_enter(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_SAFE;
    
    // SAFE behavior
    // uml: enter / { SupervisorMbd_logStateEntry("SAFE"); SupervisorMbd_enterSafeState(); }
    {
        // Step 1: execute action `SupervisorMbd_logStateEntry("SAFE"); SupervisorMbd_enterSafeState();`
        SupervisorMbd_logStateEntry("SAFE"); SupervisorMbd_enterSafeState();
    } // end of behavior for SAFE
}

static void SAFE_exit(FailoverSupervisor* sm)
{
    sm->state_id = FailoverSupervisor_StateId_ROOT;
}

static void SAFE_ev_primary_heartbeat_ok(FailoverSupervisor* sm)
{
    // SAFE behavior
    // uml: EV_PRIMARY_HEARTBEAT_OK / { SupervisorMbd_logEvent("IGNORED_PRIMARY_HEARTBEAT_IN_SAFE"); }
    {
        // Step 1: execute action `SupervisorMbd_logEvent("IGNORED_PRIMARY_HEARTBEAT_IN_SAFE");`
        SupervisorMbd_logEvent("IGNORED_PRIMARY_HEARTBEAT_IN_SAFE");
    } // end of behavior for SAFE
    
    // No ancestor handles this event.
}

// Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
char const * FailoverSupervisor_state_id_to_string(FailoverSupervisor_StateId id)
{
    switch (id)
    {
        case FailoverSupervisor_StateId_ROOT: return "ROOT";
        case FailoverSupervisor_StateId_DEGRADED: return "DEGRADED";
        case FailoverSupervisor_StateId_FAILOVER_IN_PROGRESS: return "FAILOVER_IN_PROGRESS";
        case FailoverSupervisor_StateId_INIT: return "INIT";
        case FailoverSupervisor_StateId_NORMAL: return "NORMAL";
        case FailoverSupervisor_StateId_PRIMARY_FAULT_CANDIDATE: return "PRIMARY_FAULT_CANDIDATE";
        case FailoverSupervisor_StateId_RECOVERY_DETECTED: return "RECOVERY_DETECTED";
        case FailoverSupervisor_StateId_SAFE: return "SAFE";
        default: return "?";
    }
}

// Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
char const * FailoverSupervisor_event_id_to_string(FailoverSupervisor_EventId id)
{
    switch (id)
    {
        case FailoverSupervisor_EventId_EV_BACKUP_ACTIVATION_TIMEOUT: return "EV_BACKUP_ACTIVATION_TIMEOUT";
        case FailoverSupervisor_EventId_EV_BACKUP_ACTIVE_ACK: return "EV_BACKUP_ACTIVE_ACK";
        case FailoverSupervisor_EventId_EV_CRITICAL_FAULT: return "EV_CRITICAL_FAULT";
        case FailoverSupervisor_EventId_EV_FAULT_CONFIRMATION_REACHED: return "EV_FAULT_CONFIRMATION_REACHED";
        case FailoverSupervisor_EventId_EV_INIT_DONE: return "EV_INIT_DONE";
        case FailoverSupervisor_EventId_EV_MANUAL_FAILBACK_APPROVED: return "EV_MANUAL_FAILBACK_APPROVED";
        case FailoverSupervisor_EventId_EV_PRIMARY_HEARTBEAT_OK: return "EV_PRIMARY_HEARTBEAT_OK";
        case FailoverSupervisor_EventId_EV_PRIMARY_HEARTBEAT_TIMEOUT: return "EV_PRIMARY_HEARTBEAT_TIMEOUT";
        case FailoverSupervisor_EventId_EV_PRIMARY_RECOVERY_DETECTED: return "EV_PRIMARY_RECOVERY_DETECTED";
        default: return "?";
    }
}

// Returns the parent state for a given state. Returns ROOT if input has no parent.
// Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
FailoverSupervisor_StateId FailoverSupervisor_get_parent_id(FailoverSupervisor_StateId id)
{
    switch (id)
    {
        case FailoverSupervisor_StateId_ROOT: return FailoverSupervisor_StateId_ROOT;
        case FailoverSupervisor_StateId_DEGRADED: return FailoverSupervisor_StateId_ROOT;
        case FailoverSupervisor_StateId_FAILOVER_IN_PROGRESS: return FailoverSupervisor_StateId_ROOT;
        case FailoverSupervisor_StateId_INIT: return FailoverSupervisor_StateId_ROOT;
        case FailoverSupervisor_StateId_NORMAL: return FailoverSupervisor_StateId_ROOT;
        case FailoverSupervisor_StateId_PRIMARY_FAULT_CANDIDATE: return FailoverSupervisor_StateId_ROOT;
        case FailoverSupervisor_StateId_RECOVERY_DETECTED: return FailoverSupervisor_StateId_ROOT;
        case FailoverSupervisor_StateId_SAFE: return FailoverSupervisor_StateId_ROOT;
        default: return FailoverSupervisor_StateId_ROOT;
    }
}
